
---- MANUAL OPERATION (JUST FOR SOME TEST)

-- CREATE - DRONE DATA FIXTURES
INSERT INTO MS_DL_DRONE (
ID, MODEL, SERIAL_NUMBER, BATTERY_CAPACITY, STATE, WEIGHT_LIMIT
) VALUES(1, 0, 'DL123456780X', 30, 0, 400.0);

INSERT INTO MS_DL_DRONE (
ID, MODEL, SERIAL_NUMBER, BATTERY_CAPACITY, STATE, WEIGHT_LIMIT
) VALUES(2, 1, 'DL12345678AX', 50, 1, 350.0);--load

INSERT INTO MS_DL_DRONE (
ID, MODEL, SERIAL_NUMBER, BATTERY_CAPACITY, STATE, WEIGHT_LIMIT
) VALUES(3, 2, 'DL12345679AX', 15, 2, 350.0);

-- CREATE - MEDICATION DATA FIXTURES
INSERT INTO MS_DL_MEDICATION (
ID, CODE, NAME, WEIGHT, IMAGE_FILENAME
) VALUES(1, 'ABCDE25', 'DROGX', 5.5, 'abcd.png');

INSERT INTO MS_DL_MEDICATION (
ID, CODE, NAME, WEIGHT, IMAGE_FILENAME
) VALUES(2, 'ABCDE30', 'MEDXX', 15.5, 'abcd.png');

INSERT INTO MS_DL_MEDICATION (
ID, CODE, NAME, WEIGHT, IMAGE_FILENAME
) VALUES(3, 'ABCDE40', 'PARAXXX', 50.5, 'abcd.png');

INSERT INTO MS_DL_MEDICATION (
ID, CODE, NAME, WEIGHT, IMAGE_FILENAME
) VALUES(4, 'ABCDE50', 'RADXXX', 500.0, 'abcd.png');

--- UPDATE - LOAD DRONE DATA FIXTURES (2 drones)
UPDATE MS_DL_MEDICATION SET DRONE_ID =  2 WHERE ID =  1;
UPDATE MS_DL_MEDICATION SET DRONE_ID =  2 WHERE ID =  2;
UPDATE MS_DL_MEDICATION SET DRONE_ID =  3 WHERE ID =  4;

--- CREATE - ACTIVITY HISTORY
INSERT INTO MS_DL_DRONE_HISTORY (ID, ORIGIN_LOCATION, DESTINATION_LOCATION,
                                 ACTIVITY_STATE, STARTED_AT, DRONE_ID, MEDICATION_ID)
VALUES (1, 'SOFIA', 'PLOVDIV', 'DELIVERING', '2023-03-10T13:13:07.5968907', 2, 1);

INSERT INTO MS_DL_DRONE_HISTORY (ID, ORIGIN_LOCATION, DESTINATION_LOCATION,
                                 ACTIVITY_STATE, STARTED_AT, DRONE_ID, MEDICATION_ID)
VALUES (2, 'SOFIA', 'VARNA', 'DELIVERING', '2023-03-10T13:13:07.5968970', 2, 2);

INSERT INTO MS_DL_DRONE_HISTORY (ID, ORIGIN_LOCATION, DESTINATION_LOCATION,
                                 ACTIVITY_STATE, STARTED_AT, DRONE_ID, MEDICATION_ID)
VALUES (3, 'SOFIA', 'BOURGAS', 'DELIVERING', '2023-03-10T16:13:07.5968907', 3, 4);

